// Criando a tabela de CATEGORIA
  CREATE TABLE categorias (
       id int NOT NULL,
       tituloCategoria varchar(40),
       descricaoCategoria varchar(100),
       primary key (id)
  );
   
  // Criando a tabela de FORNECEDOR
  CREATE TABLE fornecedores (
       id int NOT NULL,
       CNPJ varchar(20),
       razaoSocial varchar(50),
       telefone varchar(20),
       endereco varchar(60),
       contato varchar(30),
       primary key (id)
  );
   
  // Criando a tabela de PRODUTO
  CREATE TABLE produtos (
       id int NOT NULL,
       nomeProduto varchar(40),
       descricaoProduto varchar(100),
       valorUnitarioProduto float,
       quantidade int,
       quantidadeMinima int,
       idCategoria int,
       idFornecedor int,
  foreign key (idCategoria) REFERENCES categorias (id),
  foreign key (idFornecedor) REFERENCES fornecedores (id),
       primary key (id)
  );
   
  // Criando a tabela de VENDEDOR
  CREATE TABLE vendedores (
       id int NOT NULL,
       CPF varchar(14),
       nome varchar(40),
       carteiraTrabalho varchar(20),
       telefone varchar(20),
       dataAdmissao date,
       primary key (id)
  );
   
  // Criando a tabela de COMPRA
  CREATE TABLE compras (
       idCompra int NOT NULL,
       data date,
       hora varchar(5),
       valorTotal float,
       quantidade int,
       idProduto int,
       idCategoriaProduto int,
       idFornecedor int,
  foreign key (idProduto) REFERENCES produtos (id),
  foreign key (idCategoriaProduto)REFERENCES categorias (id),
  foreign key (idFornecedor) REFERENCES fornecedores (id),
       primary key (id)
  );
   
  // Criando a tabela de VENDA
  CREATE TABLE vendas (
       idVenda int NOT NULL,
       data date,
       hora varchar(5),
       valorTotal float,
       quantidade int,
       idProduto int,
       idCategoriaProduto int,
       idVendedor int,
  foreign key (idProduto) REFERENCES produtos (id),
  foreign key (idCategoriaProduto)REFERENCES categorias (id),
  foreign key (idVendedor) REFERENCES vendedores (id),
       primary key (id)
  ); 
  
  
  
  
  
  ===========================================
  
  
  
  CREATE TABLE `my_table` (
    `idt_mytable` int(10 ) NOT NULL AUTO_INCREMENT
    PRIMARY KEY (` idt_mytable`)
  ) ENGINE =InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET =latin1 COMMENT='Criando uma tabela no engine innodb';
  
  
  
  =============================================================================
  
  
  
  CREATE TABLE LOJA (
ID_LOJA SMALLINT IDENTITY PRIMARY KEY,
DS_NOME VARCHAR(20),
DS_ENDERECO VARCHAR(60),
ID_MONTADORA SMALLINT
)

CREATE TABLE MONTADORA (
ID_MONTADORA SMALLINT IDENTITY PRIMARY KEY,
DS_MONTADORA VARCHAR(20),
DS_ORIGEM VARCHAR(20)
)

CREATE TABLE MODELO (
ID_MODELO SMALLINT IDENTITY PRIMARY KEY,
DS_MODELO VARCHAR(20),
ID_MONTADORA SMALLINT,
ID_TIPO_VEICULO TINYINT,
FOREIGN KEY(ID_MONTADORA) REFERENCES MONTADORA (ID_MONTADORA)
)

CREATE TABLE TIPO_VEICULO (
ID_TIPO_VEICULO TINYINT IDENTITY PRIMARY KEY,
DS_TIPO_VEICULO VARCHAR(20)
)

CREATE TABLE OFICINA (
ID_OFICINA SMALLINT IDENTITY PRIMARY KEY,
DS_OFICINA VARCHAR(20),
DS_CONTATO VARCHAR(20),
DS_ENDERECO VARCHAR(60),
DS_TELEFONE VARCHAR(12),
DS_OBS VARCHAR(255),
ID_MONTADORA SMALLINT,
FOREIGN KEY(ID_MONTADORA) REFERENCES MONTADORA (ID_MONTADORA)
)

CREATE TABLE MANUTENCAO_PRODUTO (
VL_COBRADO DECIMAL(10,2),
ID_FABRICANTE SMALLINT,
ID_PRODUTO SMALLINT,
ID_MANUTENCAO INT
)

CREATE TABLE MANUTENCAO_PECA (
VL_COBRADO DECIMAL(10,2),
ID_MANUTENCAO INT,
ID_PECA SMALLINT,
ID_FABRICANTE SMALLINT
)

CREATE TABLE SERVICO (
ID_SERVICO SMALLINT IDENTITY PRIMARY KEY,
DS_SERVICO VARCHAR(30)
)

CREATE TABLE PECA (
ID_PECA SMALLINT IDENTITY PRIMARY KEY,
DS_PECA VARCHAR(20),
FL_ORIGINAL BIT
)

CREATE TABLE VEICULO (
ID_RENAVAM INT PRIMARY KEY,
DS_COR VARCHAR(20),
VL_ANO_MODELO TINYINT,
VL_ANO_FABRICACAO TINYINT,
DS_OBS VARCHAR(255),
DT_COMPRA DATETIME,
VL_COMPRA DECIMAL(10,2),
VL_KM_COMPRA SMALLINT,
DT_VENDA DATETIME,
ID_MODELO SMALLINT,
ID_LOJA SMALLINT,
FOREIGN KEY(ID_MODELO) REFERENCES MODELO (ID_MODELO),
FOREIGN KEY(ID_LOJA) REFERENCES LOJA (ID_LOJA)
)

CREATE TABLE FABRICANTE (
ID_FABRICANTE SMALLINT IDENTITY PRIMARY KEY,
DS_FABRICANTE VARCHAR(20)
)

CREATE TABLE PRODUTO (
ID_PRODUTO SMALLINT IDENTITY PRIMARY KEY,
DS_PRODUTO VARCHAR(20)
)

CREATE TABLE MANUTENCAO (
ID_MANUTENCAO INT IDENTITY PRIMARY KEY,
DS_MANUTENCAO VARCHAR(50),
DT_DATA DATETIME,
ID_OFICINA SMALLINT,
ID_RENAVAM INT,
FOREIGN KEY(ID_OFICINA) REFERENCES OFICINA (ID_OFICINA),
FOREIGN KEY(ID_RENAVAM) REFERENCES VEICULO (ID_RENAVAM)
)

CREATE TABLE FABRICANTE_PECA (
ID_FABRICANTE SMALLINT,
ID_PECA SMALLINT,
FOREIGN KEY(ID_FABRICANTE) REFERENCES FABRICANTE (ID_FABRICANTE),
FOREIGN KEY(ID_PECA) REFERENCES PECA (ID_PECA)
)

CREATE TABLE FABRICANTE_PRODUTO (
ID_FABRICANTE SMALLINT,
ID_PRODUTO SMALLINT,
FOREIGN KEY(ID_FABRICANTE) REFERENCES FABRICANTE (ID_FABRICANTE),
FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO (ID_PRODUTO)
)

CREATE TABLE MANUTENCAO_SERVICO (
VL_COBRADO DECIMAL(10,2),
ID_MANUTENCAO INT,
ID_SERVICO SMALLINT,
FOREIGN KEY(ID_MANUTENCAO) REFERENCES MANUTENCAO (ID_MANUTENCAO),
FOREIGN KEY(ID_SERVICO) REFERENCES SERVICO (ID_SERVICO)
)

ALTER TABLE LOJA ADD FOREIGN KEY(ID_MONTADORA) 
REFERENCES MONTADORA (ID_MONTADORA)

ALTER TABLE MODELO ADD FOREIGN KEY(ID_TIPO_VEICULO) 
REFERENCES TIPO_VEICULO (ID_TIPO_VEICULO)

ALTER TABLE MANUTENCAO_PRODUTO ADD FOREIGN KEY(ID_FABRICANTE)
REFERENCES FABRICANTE (ID_FABRICANTE)
ALTER TABLE MANUTENCAO_PRODUTO ADD FOREIGN KEY(ID_PRODUTO) 
REFERENCES PRODUTO (ID_PRODUTO)
ALTER TABLE MANUTENCAO_PRODUTO ADD FOREIGN KEY(ID_MANUTENCAO)
REFERENCES MANUTENCAO (ID_MANUTENCAO)
ALTER TABLE MANUTENCAO_PECA ADD FOREIGN KEY(ID_MANUTENCAO)
REFERENCES MANUTENCAO (ID_MANUTENCAO)
ALTER TABLE MANUTENCAO_PECA ADD FOREIGN KEY(ID_PECA)
REFERENCES PECA (ID_PECA)
ALTER TABLE MANUTENCAO_PECA ADD FOREIGN KEY(ID_FABRICANTE)
REFERENCES FABRICANTE (ID_FABRICANTE)